apiVersion: v1
kind: Pod
metadata:
    name: httpd-pod
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80  
    env:
      - name: BATCH
        value: "56"
      - name: ENVIRONMENT
        value: dev 
      - name: MONGO_URL 
        value: "mongo.msx.com"
      - name: BU
        value: payment


# 1) What if you have multiple environment values to be supplied to the deployment ??? 
# 2) What if you have 8 values that are common ........
# ----  configMap : this is a configMap is a placeHolder to capture all the values and supply it.
