# creating configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: https-cm
data:
  BATCH: "56"
  ENV: dev 
  MONGO_URL: "mongo.msx.com"
  APP: ecomm 

--- 

apiVersion: v1
kind: Pod
metadata:
    name: https-pod
spec:
  containers:
  - name: httpd
    image: httpd
    envFrom: 
    - configMapRef:
          name: httpd-cm

--- 

apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
spec:
  containers:
  - name: httpd
    image: nginx
    envFrom: 
    - configMapRef:
          name: httpd-cm