# creating configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-cm
data:
  BATCH: "56"
  ENV: dev 
  MONGO_URL: "mongo.msx.com"
  APP: ecomm 

--- 

apiVersion: v1
kind: Pod
metadata:
    name: httpd-pod
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80 
    envFrom: 
      - configMapRef:
          name: ecomm-cm