# creating secret
apiVersion: v1
kind: Secret
metadata:
  name: https-secret
data:
  DBPWD: cHN3MTJkCg==
  APITOKEN: Y2JoaXdubG9pd2V2a2pzZWlvdXR0dmpuZGtmCg==

--- 

apiVersion: v1
kind: Pod
metadata:
    name: secret-pod
spec:
  containers:
  - name: secret
    image: httpd
    envFrom: 
      - secretRef:
            name: https-secret 