# creating secret
apiVersion: v1
kind: Secret
metadata:
  name: https-secret
data:
  DBPWD: psw12d
  APITOKEN: cbhiwnloiwevkjseiouttvjndkf



--- 

apiVersion: v1
kind: Pod
metadata:
    name: secret-pod
spec:
  containers:
  - name: secret
    image: httpd
    envFrom: 
    - configMapRef:
          name: https-secret