# Multi Container Pod 
apiVersion: v1
kind: Pod
metadata:
  name: pod-3 
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    env: 
    - name: BATCH
      value: "55"                      # Ensure you enclose the numericals in quotes
    - name: ENVIRONMENT
      value: dev 
    - name: MONGO_URL
      value: mongo.corp.cc 
    - name: BU 
      value: ecomm

--- 

apiVersion: v1
kind: Pod
metadata:
  name: pod-4 
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    env: 
    - name: BATCH
      value: "55"                      # Ensure you enclose the numericals in quotes
    - name: ENVIRONMENT
      value: dev 
    - name: MONGO_URL
      value: mongo.corp.cc 
    - name: BU 
      value: ecomm


# What if you have 10 environment variables ?
# What if you have 10 environment variables and all of them are common to all of your 10 pods ?
# * Do you delcare them 10 times ? configMap 